### ISSUE TITLE
和约束布局配合会报错

### ISSUE THREAD

**Issue by OnClickListener2048** [li-xiaojun/StateLayout#8]
当要wrap的View的父View是约束布局 运行时会报强制转换异常  希望能尽快修复
 java.lang.ClassCastException: android.widget.FrameLayout$LayoutParams cannot be cast to androidx.constraintlayout.widget.ConstraintLayout$LayoutParams
        at androidx.constraintlayout.widget.ConstraintLayout.getTargetWidget(ConstraintLayout.java:1144)
        at androidx.constraintlayout.widget.ConstraintLayout.setChildrenConstraints(ConstraintLayout.java:1028)
        at androidx.constraintlayout.widget.ConstraintLayout.updateHierarchy(ConstraintLayout.java:803)
        at androidx.constraintlayout.widget.ConstraintLayout.onMeasure(ConstraintLayout.java:1561)
        at android.view.View.measure(View.java:20188)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6282)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:214)
        at android.view.View.measure(View.java:20188)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6282)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1705)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:797)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:657)
        at android.view.View.measure(View.java:20188)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6282)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:214)
        at com.android.internal.policy.DecorView.onMeasure(DecorView.java:713)
        at android.view.View.measure(View.java:20188)
        at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2673)
        at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1603)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1876)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1488)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7095)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:921)
        at android.view.Choreographer.doCallbacks(Choreographer.java:723)
        at android.view.Choreographer.doFrame(Choreographer.java:658)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:907)
        at android.os.Handler.handleCallback(Handler.java:836)
        at android.os.Handler.dispatchMessage(Handler.java:103)
        at android.os.Looper.loop(Looper.java:203)
        at android.app.ActivityThread.main(ActivityThread.java:6406)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1113)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:974)

**Comment by OnClickListener2048** [comment]
另外建议增加一个可以让用户选择初始化布局的功能  比如我只需要一个loading 布局其他不想要此时就初始化一个
